using System;
using System.Collections.Generic;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
#endif

namespace ODDGames.UITest.VisualBuilder
{
    /// <summary>
    /// A codeless UI test defined as a sequence of visual blocks.
    /// Can be created manually via the Visual Test Builder or generated by AI recording.
    /// </summary>
    [CreateAssetMenu(fileName = "NewVisualTest", menuName = "UITest/Visual Test")]
    public class VisualTest : ScriptableObject
    {
        [Header("Test Info")]
        [Tooltip("Display name for this test")]
        public string testName;

        [TextArea(2, 4)]
        [Tooltip("Description of what this test verifies")]
        public string description;

        [Header("Scene")]
        [Tooltip("The scene to load before running this test")]
        public string startScene;

        [Header("Test Steps")]
        [Tooltip("Ordered list of action blocks that make up this test")]
        public List<VisualBlock> blocks = new();

        [Header("Test Data")]
        [Tooltip("Data files bundled with this test for persistent data operations")]
        public List<TestDataFile> testDataFiles = new();

        [Header("AI Recording (if generated)")]
        [TextArea(2, 5)]
        [Tooltip("Original natural language prompt used to generate this test")]
        public string originalPrompt;

        /// <summary>
        /// Adds a new block to the test.
        /// </summary>
        public VisualBlock AddBlock(BlockType type)
        {
            var block = new VisualBlock
            {
                id = Guid.NewGuid().ToString(),
                type = type
            };
            blocks.Add(block);
            return block;
        }

        /// <summary>
        /// Removes a block by ID.
        /// </summary>
        public bool RemoveBlock(string blockId)
        {
            return blocks.RemoveAll(b => b.id == blockId) > 0;
        }

        /// <summary>
        /// Moves a block to a new index.
        /// </summary>
        public void MoveBlock(int fromIndex, int toIndex)
        {
            if (fromIndex < 0 || fromIndex >= blocks.Count) return;
            if (toIndex < 0 || toIndex >= blocks.Count) return;

            var block = blocks[fromIndex];
            blocks.RemoveAt(fromIndex);
            blocks.Insert(toIndex, block);
        }

        /// <summary>
        /// Gets a block by ID.
        /// </summary>
        public VisualBlock GetBlock(string blockId)
        {
            return blocks.Find(b => b.id == blockId);
        }

        /// <summary>
        /// Duplicates a block and inserts the copy after the original.
        /// </summary>
        public VisualBlock DuplicateBlock(string blockId)
        {
            var original = GetBlock(blockId);
            if (original == null) return null;

            var copy = original.Clone();
            copy.id = Guid.NewGuid().ToString();

            int index = blocks.IndexOf(original);
            blocks.Insert(index + 1, copy);
            return copy;
        }
    }
}
